//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STL_Showcase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PreferredCachePath {
            get {
                return ((int)(this["PreferredCachePath"]));
            }
            set {
                this["PreferredCachePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDirectory {
            get {
                return ((string)(this["LastDirectory"]));
            }
            set {
                this["LastDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RenderAspect {
            get {
                return ((int)(this["RenderAspect"]));
            }
            set {
                this["RenderAspect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentView3DAspect {
            get {
                return ((int)(this["CurrentView3DAspect"]));
            }
            set {
                this["CurrentView3DAspect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainColumnsVisibilityDirectoryTree {
            get {
                return ((bool)(this["MainColumnsVisibilityDirectoryTree"]));
            }
            set {
                this["MainColumnsVisibilityDirectoryTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainColumnsVisibilityModelList {
            get {
                return ((bool)(this["MainColumnsVisibilityModelList"]));
            }
            set {
                this["MainColumnsVisibilityModelList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainColumnsVisibility3DView {
            get {
                return ((bool)(this["MainColumnsVisibility3DView"]));
            }
            set {
                this["MainColumnsVisibility3DView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainColumnsPoweredIndex {
            get {
                return ((int)(this["MainColumnsPoweredIndex"]));
            }
            set {
                this["MainColumnsPoweredIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastLoadedDirectories {
            get {
                return ((string)(this["LastLoadedDirectories"]));
            }
            set {
                this["LastLoadedDirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigLinkedProgramsList {
            get {
                return ((string)(this["ConfigLinkedProgramsList"]));
            }
            set {
                this["ConfigLinkedProgramsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDebugLogs {
            get {
                return ((bool)(this["EnableDebugLogs"]));
            }
            set {
                this["EnableDebugLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Thumbnails3DAspect {
            get {
                return ((int)(this["Thumbnails3DAspect"]));
            }
            set {
                this["Thumbnails3DAspect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTreeCollections {
            get {
                return ((bool)(this["EnableTreeCollections"]));
            }
            set {
                this["EnableTreeCollections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTreeOnlyFolders {
            get {
                return ((bool)(this["EnableTreeOnlyFolders"]));
            }
            set {
                this["EnableTreeOnlyFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMeshDecimation {
            get {
                return ((bool)(this["EnableMeshDecimation"]));
            }
            set {
                this["EnableMeshDecimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int MinTrianglesForMeshDecimation {
            get {
                return ((int)(this["MinTrianglesForMeshDecimation"]));
            }
            set {
                this["MinTrianglesForMeshDecimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int MaxSizeMBToLoadMeshInView {
            get {
                return ((int)(this["MaxSizeMBToLoadMeshInView"]));
            }
            set {
                this["MaxSizeMBToLoadMeshInView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMaxSizeMBToLoadMeshInView {
            get {
                return ((bool)(this["EnableMaxSizeMBToLoadMeshInView"]));
            }
            set {
                this["EnableMaxSizeMBToLoadMeshInView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableReduceThumbnailQuality {
            get {
                return ((bool)(this["EnableReduceThumbnailQuality"]));
            }
            set {
                this["EnableReduceThumbnailQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableReduceThumbnailResolution {
            get {
                return ((bool)(this["EnableReduceThumbnailResolution"]));
            }
            set {
                this["EnableReduceThumbnailResolution"] = value;
            }
        }
    }
}
